### ISSUE TITLE
[Improper parsing]: 6MB file doesn't load in the Burp Extension

### ISSUE THREAD

**Issue by antoniolortenford** [doyensec/inql#109]
### InQL version

BApp Store

### What isn't working?

I'm choosing the json file in the Burp Extension, but it doesn't load. 
I was able to upload the same file to 'graphl-voyager' and it worked.
It's a big file, almost 6 MB but it's not broken.
[schemaa.zip](https://github.com/doyensec/inql/files/11472194/schemaa.zip)

**Comment by antoniolortenford** [comment]
I forgot to add the minified version of the json, that it's 4MB, here it is. 
[schema_mini.zip](https://github.com/doyensec/inql/files/11472187/schema_mini.zip)

**Comment by execveat** [comment]
Hey, @antoniolortenford! Thank you for reporting a bug.

What is the source of this schema? I'd love to add some real-world schemas to our test suite in order to track regressions.

Parsing works without any issues. Given a large number of queries you might want to use our CLI tool for that (use dev branch for now: https://github.com/doyensec/gqlspection/tree/dev):

```bash
$ gqlspection -f schemaa.json
```

InQL had trouble displaying more than 400 files per folder, but I just pushed fixes, so the next release should support this use case as well.

**Comment by antoniolortenford** [comment]
Thanks for the information and for looking into this problem!
I'm struggling with the CLI version because the schema contains many comments, and the GUI/Extender version auto-fills the format when it has input and removes the comments. (If I'm not mistaken)

This schema is from Indeed, this is the endpoint: https://apis.indeed.com/graphql
In the image example, I tried to test the query "conversation" but it has so many comments that it's hard to build the query.

Probably I'll wait until the next release

![image](https://github.com/doyensec/inql/assets/126786084/13dbe2b2-b84d-48ea-b649-cc252c3b58d8)
