### ISSUE TITLE
Does not take graphql endpoints [invalid]

### ISSUE THREAD

**Issue by websecnl** [doyensec/inql#31]
It requires /qraphql as URI

but my endpoint is on /   , it doesn't seem to work on /  (root directory graphql endpoint)

**Comment by thypon** [comment]
Can you share more context?
It actually works even with non /graphql endpoints, with some caveats, but I need to be able to debug your particular case.

**Comment by thypon** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 16.04, Windows 10, macOS Catalina]
 - Java Version: [e.g. java -v output, if applicable]
- Python Version: [e.g. Jython v2.7.0/Python 3.4.3]
- Burp Version: [eg. 2.1.0 if applicable]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here.
