### ISSUE TITLE
GraphiQL feature is not working

### ISSUE THREAD

**Issue by realArcherL** [doyensec/inql#72]
**Describe the bug**
Hi, I am trying to send the request from the repeater tab to the GraphiQL and for some reason the server just fails to load.
Ex: I have a query and send it to graphiql -> we are taken to the default browser (in my case the default browser is not the one used by Burp) localhost:64235 -> It doesn't load or keeps loading

**To Reproduce**
1. Find a website with GraphQL (ex: infosechub.io)
2. Open the tool, intercetp the request, send it to the GraphiQL
3. The website (localhost server) doesn't work.

**Expected behavior**
It should be loading and allow users to send graphql request via graphql playground.

**Screenshots**
<img width="244" alt="image" src="https://user-images.githubusercontent.com/42532003/203437734-75ca87c7-b1df-4220-9596-22c0ec21c9bb.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 
- Python Version: Python 3.10.8
- Burp Version: Burp CEv2022.9.6 
 - Version: latest

**Additional context**
Add any other context about the problem here. Might be similar to this https://github.com/doyensec/inql/pull/62

**Comment by execveat** [comment]
Hi, @realArcherL! You seem to be using the InQL version from BApp Store and this issue has been fixed in the master (but not released to the BApp Store just yet).

Please try building the InQL from the github repo (should be as easy as `pip install -r requirements.txt && make ext/ext/inql_burp.py`. If you don't have a development environment, here's a pre-built inql_burp.py.

[inql_burp.py.zip](https://github.com/doyensec/inql/files/10073332/inql_burp.py.zip)

Just unload existing version from BApp Store and import the inql_burp.py instead.

P.S. The API you mentioned requires authorization, so you'd need to add custom headers (right click -> Set Custom Header). I'm not sure that it will work with GraphiQL though. If it doesn't, please create a new issue!
